config/routes.rb
ItemApp::Application.routes.draw do

  root to: 'main#index'

  resources :items

end

app/models/item.rb
# -*- encoding: utf-8 -*-

class Item < ActiveRecord::Base

  attr_accessible :name, :picture

  has_attached_file :picture,
                    styles: { thumb: '100x100#' },
                    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  validates :name, presence: true

  scope :ordered, order(:id.desc)

  def picture_for_list
    self.picture.url(:thumb)
  end
end

app/controllers/application_controller.rb
# -*- encoding: utf-8 -*-

class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def list_items
    @items ||= Item.ordered
  end
end

app/controllers/items_controller.rb
# -*- encoding: utf-8 -*-

class ItemsController < ApplicationController

  before_filter :list_items, only: [:create]
  before_filter :load_item, only: [:edit, :update, :destroy]

  respond_to :js

  def edit; end

  def create
    build_item and save_item
  end

  def update
    build_item and save_item if @item.present?
  end

  def destroy
    destroy_item
  end

  private

  def build_item
    @item ||= item_scope.build
    @item.attributes = params[:item] || {}
  end

  def load_item
    @item ||= item_scope.find(params[:id])
  end

  def save_item
    unless @item.save
      flash.now[:error] = error_messages
    end
  end

  def destroy_item
    @item.destroy if @item.present?
  end

  def item_scope
    Item.scoped
  end

  def error_messages
    @item.errors.full_messages.join('<br />')
  end
end

app/controllers/main_controller.rb
# -*- encoding: utf-8 -*-

class MainController < ApplicationController

  before_filter :build_item, only: :index
  before_filter :list_items, only: :index

  def index; end

  private

  def build_item
    @item = Item.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/items/_form.html.slim
span.form-header = form_title

div.form-container
  = form_for @item, html: { class: 'form-inline', role: 'form', multipart: true }, remote: true do |f|
    div.row
      div.form-group
        = f.text_field :name, class: 'form-control input-title', placeholder: 'Название'
      div.form-group
        = f.file_field :picture, title: image_title
      div.form-group
        = f.submit 'Сохранить', class: 'btn btn-primary', disable_with: 'Отправляется...'
    - if @item.new_record?
      div.row.errors-container id="new-error"
    - else
      div.row.errors-container id="edit-error-#{@item.id}"
      a.cancel-edit-form href="#" data-edit-form-id="#{@item.id}" Отменить редактирование

app/views/items/_item.html.slim
tr id="item-#{item.id}"
  td.col-md-5 = item.name
  td.col-md-3
    img src="#{item.picture_for_list}" alt='' class='img-thumbnail'
  td.col-md-2.action-block
    = link_to 'Редактировать', edit_item_path(item.id), remote: true
  td.col-md-2.action-block
    = link_to 'Удалить', item_path(item.id), remote: true, method: :delete, confirm: 'Удалить?'

  tr.edit-item-row id="edit-item-row-#{item.id}"
    td colspan='4'

app/views/items/_list-items.html.slim
span.list-header
  | Список Item'ов

  div.list-container

    table.list-table
      - @items.each do |item|
        = render partial: 'items/item', locals: { item: item }

app/views/items/create.js.erb
item_app.clear_new_form();

<% if flash.now[:error].present? %>
  $('#new-error').html("<%= j flash.now[:error] -%>").show();
<% else %>
  $('#new-error').html('').hide();
  $('#list-items').html("<%= j render(partial: 'list-items') -%>");
<% end %>

app/views/items/destroy.js.erb
<% if @item.present? %>
  $("#edit-item-row-<%= @item.id -%>").remove();
  $('#item-<%= @item.id -%>').remove();
<% end %>

app/views/items/edit.js.erb
<% if @item.present? %>
  $("#edit-item-row-<%= @item.id -%> > td").
        html("<%= j render(partial: 'items/form', locals: { form_title: 'Редактирование Item\'а', image_title: '+ Заменить картинку' }) -%>");

  item_app.decorate_file_input(
          $("#edit-item-row-<%= @item.id -%>").find('input[type=file]')
  );
  item_app.observe_form(
          $("#edit-item-row-<%= @item.id -%>")
  );
  $("#edit-item-row-<%= @item.id -%>").show();
<% end %>

app/views/items/update.js.erb
<% if flash.now[:error].present? %>
  $('#edit-error-<%= @item.id -%>').html("<%= j flash.now[:error] -%>").show();
<% else %>
  $("#edit-item-row-<%= @item.id -%>").remove();
  $('#item-<%= @item.id -%>').replaceWith(
        "<%= j render(partial: 'items/item', locals: { item: @item }) -%>"
  );
<% end %>

app/views/layouts/application.html.slim
doctype html

html
  head
    title ItemApp

    = stylesheet_link_tag :application, media: 'all'
    = javascript_include_tag :application

    = csrf_meta_tags

  body
    = yield

app/views/main/index.html.slim
h1.header Items

div.container-fluid

  == render partial: 'items/form', locals: { form_title: 'Форма добавления нового Item\'а', image_title: '+ Прикрепить картинку' }

  div#list-items
    == render 'items/list-items'